import './utils/fetch'
import './utils/normalizeOperation'
import './utils/normalizeResource'
import './utils/addNamesToResources'
import './utils/mergeResponse'
import './utils/getUri'
import './utils/getMethod'

import './resourcesMutator/index'
import './resourcesMutator/createMutator'
